# ---
# -
#   gather_facts: false
#   hosts: localhost
#   tasks:
#     -
#       k8s:
#         definition: "{{ item }}"
#         kubeconfig: "{{ k8s_kubeconfig }}"
#         state: present
#       loop: "{{ lookup('template', 'wordpress/mysql-pass.yml') | from_yaml_all | list }}"
#       name: "Deploy WordPress secrets."
#       no_log: k8s_no_log
#     -
#       k8s:
#         definition: "{{ item }}"
#         kubeconfig: "{{ k8s_kubeconfig }}"
#         state: present
#       loop:
#         - "{{ lookup('template', 'wordpress/mysql.yml') | from_yaml_all | list }}"
#         - "{{ lookup('template', 'wordpress/wordpress.yml') | from_yaml_all | list }}"
#       name: "Deploy MySQL and WordPress."
#   vars_files:
#     - vars/main.yml
---
-
  #command: "kubectl apply -f wordpress/mysql-pass.yml"
  hosts: localhost
  name: Deploy
  tasks:
    # -
    #   name: "deploy mysql pass"
    #   register: output
    #   shell: "kubectl apply -f wordpress/mysql-pass.yml"
    # -
    #   name: "deploy mysql db"
    #   register: output
    #   shell: "kubectl apply -f wordpress/mysql.yml"
    -
      name: "wordpress codebase"
      register: output
      shell: "kubectl apply -f deploy1.yml"
    -
      debug: var=output.stdout_lines




